trigger:
- main

pool:
  name: Default

steps:
- script: dotnet restore HelloWorld/HelloWorld.csproj
  displayName: 'Restore dependencies'

- script: dotnet build HelloWorld/HelloWorld.csproj --configuration Release
  displayName: 'Build project'

- script: dotnet run --project HelloWorld/HelloWorld.csproj
  displayName: 'Run application'
