trigger:
- main

pool:
  name: Default

steps:
- script: dotnet restore HelloWorld/HelloWorld.csproj /p:Version=1.0.$(Build.BuildId)
  displayName: 'Restore dependencies'

- script: dotnet build HelloWorld/HelloWorld.csproj --configuration Release /p:Version=1.0.$(Build.BuildId)
  displayName: 'Build project'

- script: |
    echo "Current Version: 1.0.$(Build.BuildId)"
  displayName: 'Print Version'

- script: dotnet pack HelloWorld/HelloWorld.csproj --configuration Release --output nupkgs /p:Version=1.0.$(Build.BuildId)
  displayName: 'Pack NuGet package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'HelloWorld/bin/Release'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: dotnet nuget push "nupkgs/*.nupkg" --source "https://pkgs.dev.azure.com/OriElias/_packaging/OriElias/nuget/v3/index.json" --api-key az --skip-duplicate
  displayName: 'Push package to Azure Artifacts'

- script: dotnet run --project HelloWorld/HelloWorld.csproj
  displayName: 'Run application'
