trigger:
  branches:
    include:
    - main
    - sonar-scan

pool:
  name: Default

steps:
- script: |
    echo Installing sonarScanner tool
    dotnet tool install --global dotnet-sonarscanner
    export PATH="$PATH:$HOME/.dotnet/tools"
    
    echo Start Scanner
    dotnet-sonarscanner begin /k:"Hello_World_Project_Hello_World_Project_AYxio5OHkVImKS8uzBdC" /d:sonar.host.url="http://172.31.23.61:9000" /d:sonar.login="sqa_31544eab9ab4db6d9aa773d388879ba8d787d685"
  displayName: 'Install Sonar Tools and Start Scanner'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/sonar-scan')

- script: dotnet restore HelloWorld/HelloWorld.csproj /p:Version=1.0.$(Build.BuildId)
  displayName: 'Restore dependencies'

- script: dotnet build HelloWorld/HelloWorld.csproj --configuration Release /p:Version=1.0.$(Build.BuildId)
  displayName: 'Build project'

- script: |
    echo Run Sonar End
    export PATH="$PATH:$HOME/.dotnet/tools"
    dotnet-sonarscanner end /d:sonar.login="sqa_31544eab9ab4db6d9aa773d388879ba8d787d685"
  displayName: 'Collect Sonar results and Upload'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/sonar-scan')

- script: |
    echo "Current Version: 1.0.$(Build.BuildId)"
  displayName: 'Print Version'

- script: dotnet pack HelloWorld/HelloWorld.csproj --configuration Release --output nupkgs /p:Version=1.0.$(Build.BuildId)
  displayName: 'Pack NuGet package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'HelloWorld/bin/Release'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: dotnet nuget push "nupkgs/*.nupkg" --source "https://pkgs.dev.azure.com/OriElias/_packaging/OriElias/nuget/v3/index.json" --api-key az --skip-duplicate
  displayName: 'Push package to Azure Artifacts'

- script: dotnet run --project HelloWorld/HelloWorld.csproj
  displayName: 'Run application'
